# No banner
spring:
  main:
    banner-mode: off

# Formpipe Proxy integration
integration:
  formpipe-proxy:
    base-url: ${env.FORMPIPE_PROXY_BASE_URL}
    connect-timeout: ${env.FORMPIPE_PROXY_CONNECT_TIMEOUT:10s}
    read-timeout: ${env.FORMPIPE_PROXY_READ_TIMEOUT:30s}

# Archive settings
byggr:
  submission-agreement-id: ${env.BYGGR_SUBMISSION_AGREEMENT_ID}

