version: '3'
services:
  archive:
    container_name: ms-archive-sandbox
    image: 'ms-archive:latest'
    restart: always
    depends_on:
      - ms-archive-sandbox-wiremock
    links:
      - ms-archive-sandbox-wiremock:wiremock
    ports:
      - '9051:8080'
    environment:
      - JAVA_OPTS=-server -Dfile.encoding=UTF-8 -Xms128m -Xmx256m
      - SPRING_PROFILES_ACTIVE=sandbox
      - FORMPIPE_PROXY_BASE_URL=http://wiremock:8080/formpipe-proxy
      - BYGGR_SUBMISSION_AGREEMENT_ID=AGS

  ms-archive-sandbox-wiremock:
    container_name: ms-archive-sandbox-wiremock
    image: wiremock/wiremock:2.32.0
    restart: always
    expose:
      - '8080'
    volumes:
      - $PWD/src/sandbox/wiremock:/home/wiremock
