version: "3"
services:
  archive:
    container_name: ms-archive-test
    image: 'ms-archive:latest'
    network_mode: bridge
    restart: always
    ports:
      - "9050:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - FORMPIPE_PROXY_BASE_URL=